name: Terraform Plan

on:
  push:
    branches-ignore:
      - main

jobs:
  lint_and_scan:
    name: Lint and Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      # - name: Run Trivy vulnerability scanner in IaC mode
        # uses: aquasecurity/trivy-action@master
        # with:
        #   scan-type: 'config'
        #   hide-progress: false
        #   format: 'table'
        #   exit-code: '1'
        #   ignore-unfixed: true
        #   severity: 'CRITICAL,HIGH'

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

  plan:
    name: Dev Terraform Plan
    runs-on: ubuntu-latest
    needs: lint_and_scan
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::499497677544:role/GithubOIDC"
          aws-region: "eu-west-2"

      - name: Dev Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Dev Init Terraform
        working-directory: terraform
        run: terraform init -backend-config=terraform/environments/developement/dev.tfvars

      - name: Dev Terraform Plan
        working-directory: terraform
        run: terraform plan -var-file=terraform/environments/developement/dev.tfvars